### ISSUE TITLE
看到techguy移除项目，万分心疼，大佬会延续传奇吗？

### ISSUE THREAD

**Issue by lele2010lele** [Cabchinoe/v9porn#1]
18年就关注了techguy大神，这几个月没关注github，找了好几个月才发现您这有fork.
敢问大神会续写V9porn的传奇吗？哪怕是需要资助您说句话。

**Comment by Cabchinoe** [comment]
停止维护, 代码还在, 某部分revert到之前的版本仍可用, 君可自行修改编译, 欢迎PR

**Comment by Cabchinoe** [comment]
> 18年就关注了techguy大神，这几个月没关注github，找了好几个月才发现您这有fork.
> 敢问大神会续写V9porn的传奇吗？哪怕是需要资助您说句话。

停止维护, 代码还在, 某部分revert到之前的版本仍可用, 君可自行修改编译, 欢迎PR

**Comment by Somerhi** [comment]
大神,porn中的视频地址如何获取?
